"""added column to courses table

Revision ID: 5ef93b71b3d6
Revises: 47492f3ec636
Create Date: 2025-09-12 20:39:32.772122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef93b71b3d6'
down_revision = '47492f3ec636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('mentor_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mentor_name', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
